import React from 'react';
import { useParams, Link, Navigate } from 'react-router-dom';
import { ArrowLeft, GitBranch, Database, Server, Component } from 'lucide-react';
import ImageCarousel from '../ui/ImageCarousel';

const Highlight = ({ children }) => (
  <span className="text-cyan-400 font-mono text-sm bg-cyan-950/30 px-1.5 py-0.5 rounded border border-cyan-500/20">
    {children}
  </span>
);

const projectsData = {
  "statbot-pro": {
    title: "StatBot Pro (Autonomous AI Data Analyst)",
    techStack: ['Python', 'FastAPI', 'React', 'Docker', 'Groq', 'Llama-3', 'LangChain'],
    github: "https://github.com/maCkey023/statbot-pro",
    headerMedia: (
      <div className="max-w-4xl mx-auto rounded-xl overflow-hidden shadow-[0_0_40px_rgba(6,182,212,0.15)] border border-zinc-800 aspect-[16/9] mb-16 relative">
        <iframe 
          width="100%" height="100%" className="absolute top-0 left-0"
          src="https://www.youtube.com/embed/vJlSuDJI4O0?rel=0" 
          title="StatBot Pro Demo" frameBorder="0" 
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen
        ></iframe>
      </div>
    ),
    content: (
      <>
        <p className="text-zinc-300 text-lg leading-relaxed mb-8">
          StatBot Pro is an autonomous, AI-powered data analyst that transforms plain English queries into executed Python code and interactive visualizations. Engineered with a decoupled React and FastAPI architecture, it leverages Llama-3 to stream real-time reasoning while securely executing generated code within a hardened, unprivileged Docker sandbox.
        </p>

        <h2 className="text-2xl font-bold mb-4 text-white border-b border-zinc-800 pb-2 mt-12">The Problem It Solves</h2>
        <p className="text-zinc-300 mb-8">
          Data analysis typically requires extensive knowledge of Python, Pandas, and data visualization libraries. StatBot Pro bridges this gap by acting as an autonomous data analyst. Instead of wrestling with complex syntax, users simply upload a CSV dataset and ask questions in plain English. The AI agent translates these queries, writes the necessary Python code, executes it, and delivers insights and visualizations in real-time.
        </p>

        <h2 className="text-2xl font-bold mb-4 text-white border-b border-zinc-800 pb-2 mt-12">System Architecture</h2>
        <p className="text-zinc-300 mb-6">
          The application utilizes a robust, decoupled architecture to ensure rapid frontend response times while securing potentially dangerous code executions:
        </p>
        <ul className="list-disc list-inside text-zinc-300 mb-12 space-y-3">
          <li><strong>React UI (Client):</strong> A modern Vite-powered React interface captures user prompts and CSV uploads effortlessly.</li>
          <li><strong>FastAPI (Backend):</strong> Orchestrates the AI via LangChain and the Groq API (Llama-3-70b), managing State, file I/O, and streaming responses back over WebSockets and SSE.</li>
          <li><strong>Docker Sandbox (Engine):</strong> The actual Pandas DataFrame agent operates inside a hardened Docker container, completely shielded from the host machine.</li>
        </ul>

        <h2 className="text-2xl font-bold mb-4 text-white border-b border-zinc-800 pb-2 mt-12">Security: The "Swiss Cheese Defense"</h2>
        <p className="text-zinc-300 mb-6">
          An application that executes arbitrary code generated by an AI opens severe security vulnerabilities (like Prompt Injections). StatBot mitigates this using a multi-layered defense strategy:
        </p>
        <ul className="list-disc list-inside text-zinc-300 mb-12 space-y-3">
          <li><strong>Prompt Firewall:</strong> Strict system instructions govern the agent, minimizing the chances of jailbreaks.</li>
          <li><strong>Non-Root Container:</strong> The backend container runs entirely under an unprivileged user. Even if an attacker executes code like <code>os.system('rm -rf /')</code>, they lack permissions to do meaningful damage.</li>
          <li><strong>Read-Only Mounts:</strong> Core execution directories and system paths are mounted into the container as Read-Only.</li>
        </ul>

        <h2 className="text-2xl font-bold mb-4 text-white border-b border-zinc-800 pb-2 mt-12">Key Features</h2>
        <ul className="list-disc list-inside text-zinc-300 mb-12 space-y-3">
          <li><strong>Real-Time Thought Streaming:</strong> Watch the AI's internal reasoning via a real-time SSE stream. You literally see the agent "thinking" before it acts.</li>
          <li><strong>Dynamic Chart Generation:</strong> The agent natively writes Python code to generate compelling <Highlight>matplotlib</Highlight> / <Highlight>seaborn</Highlight> visual charts, instantly injected into your chat feed.</li>
          <li><strong>Hardware-Level Security Sandboxing:</strong> All LLM-generated code runs in a strictly isolated environment, preventing malicious prompt injections.</li>
        </ul>
      </>
    )
  },
  "documind": {
    title: "DocuMind Enterprise (RAG AI)",
    techStack: ['Python', 'FastAPI', 'React', 'Pinecone', 'LangChain', 'OpenAI'],
    github: "https://github.com/maCkey023/DocuMind-Enterprise",
    headerMedia: (
      <div className="max-w-4xl mx-auto rounded-xl overflow-hidden shadow-[0_0_40px_rgba(6,182,212,0.15)] border border-zinc-800 aspect-[16/9] mb-16 relative">
        <iframe 
          width="100%" height="100%" className="absolute top-0 left-0"
          src="https://www.youtube.com/embed/TZmlJW5EXAY?rel=0" 
          title="DocuMind Enterprise Demo" frameBorder="0" 
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen
        ></iframe>
      </div>
    ),
    content: (
      <>
        <p className="text-zinc-300 text-lg leading-relaxed mb-8">
          DocuMind Enterprise is a high-performance Retrieval-Augmented Generation (RAG) system built to parse, index, and query thousands of dense PDF documents with sub-second latency. It leverages state-of-the-art vector embeddings and LLM guardrails to prevent hallucination in critical corporate environments.
        </p>
        <h2 className="text-2xl font-bold mb-4 text-white border-b border-zinc-800 pb-2 mt-12">Architecture</h2>
        <p className="text-zinc-300 mb-8">
          The backend is built entirely on asynchronous Python utilizing FastAPI for extreme throughput. The document ingestion pipeline uses chunking and parallelized embedding generation before pushing vectors to Pinecone. The querying layer enforces strict role-based access control and relevance-thresholding before generating responses.
        </p>
        <h2 className="text-2xl font-bold mb-4 text-white border-b border-zinc-800 pb-2 mt-12">Key Features</h2>
        <ul className="list-disc list-inside text-zinc-300 mb-12 space-y-2">
          <li><strong>Zero Hallucination Guardrails:</strong> Strictly limits generative scope to the retrieved context.</li>
          <li><strong>Advanced API Rate Limiting:</strong> Custom Redis-backed token bucket algorithm for endpoint protection.</li>
          <li><strong>Dynamic Source Citation:</strong> All answers provide direct clickable references to the exact page of the ingested document.</li>
          <li><strong>Real-time Analytics:</strong> Admin dashboard monitoring query volume, latency, and embedding drift.</li>
        </ul>
      </>
    )
  },
  "us-petrol": {
    title: "U.S-Petrol E-Commerce Platform",
    techStack: ['MongoDB', 'Express.js', 'React', 'Node.js', 'Tailwind', 'JWT'],
    github: "https://github.com/maCkey023/U.S-Petrol",
    headerMedia: (
      <div className="max-w-4xl mx-auto rounded-xl overflow-hidden shadow-[0_0_40px_rgba(6,182,212,0.15)] border border-zinc-800 mb-16 relative">
        <img 
          src="/images/us-petrol-schema.png" 
          alt="System Architecture Diagram" 
          className="w-full h-auto object-cover min-h-[300px] bg-zinc-900" 
          onError={(e) => {
            e.target.style.display = 'none';
            e.target.nextSibling.style.display = 'flex';
          }}
        />
        <div className="hidden absolute inset-0 items-center justify-center bg-zinc-900 text-zinc-500 font-medium">
          Architecture Diagram Image Not Found (/images/us-petrol-schema.png)
        </div>
        <div className="relative z-10 p-4 bg-zinc-900/90 backdrop-blur border-t border-zinc-800 text-center text-sm text-zinc-400">
          U.S-Petrol MERN System Architecture Overview
        </div>
      </div>
    ),
    content: (
      <>
        <p className="text-zinc-300 text-lg leading-relaxed mb-8">
          U.S-Petrol is a comprehensive MERN-stack e-commerce platform engineered specifically to handle both B2B wholesale and B2C retail transactions. It implements a secure, scalable architecture optimized for high-volume inventory streaming, role-based access control, and seamless checkout operations.
        </p>

        <h2 className="text-2xl font-bold mb-4 text-white border-b border-zinc-800 pb-2 mt-12">System Architecture Overview</h2>
        <p className="text-zinc-300 mb-8">
          The platform utilizes a decoupled MERN architecture where the <Highlight>React.js</Highlight> frontend communicates asynchronously with a robust <Highlight>Node/Express</Highlight> backend via strict <Highlight>RESTful APIs</Highlight>. State management across the client is highly optimized, minimizing re-renders during deep-cart nesting, while the backend utilizes scalable controller-service patterns to isolate business logic from network routing.
        </p>

        <h2 className="text-2xl font-bold mb-4 text-white border-b border-zinc-800 pb-2 mt-12">Authentication Flow (The Flex)</h2>
        <p className="text-zinc-300 mb-8">
          Security is fundamental to the platform. I implemented a stateless, cryptographically secure <Highlight>JWT (JSON Web Token)</Highlight> authentication pipeline. 
          Upon successful login, the server signs a <Highlight>JWT payload</Highlight> containing the user's encoded role and ID, setting it securely via <Highlight>HttpOnly cookies</Highlight> to prevent XSS attacks. 
          Every subsequent private API request passes through custom <Highlight>Express Middleware</Highlight> that decodes and validates the token signature, strictly denying unauthorized access to admin dashboards or checkout operations.
        </p>

        <h2 className="text-2xl font-bold mb-4 text-white border-b border-zinc-800 pb-2 mt-12">Database Schema Design</h2>
        <p className="text-zinc-300 mb-8">
          Data relationships are meticulously managed within the <Highlight>MongoDB / Mongoose NoSQL</Highlight> ecosystem using embedded documents and logical referencing to optimize read performance.
        </p>
        <ul className="list-disc list-inside text-zinc-300 mb-12 space-y-3">
          <li><strong>Users Collection:</strong> Stores hashed credentials (via bcrypt) and utilizes an enum `role` field (`admin`, `wholesale`, `retail`) to dynamically restrict access limits globally.</li>
          <li><strong>Products Collection:</strong> Implements comprehensive indexing on SKUs and categories for sub-millisecond querying. It includes embedded reviews and dynamic stock trackers.</li>
          <li><strong>Orders Collection:</strong> Resolves relational integrity by storing historical snapshots of product prices and user details at the exact time of checkout, ensuring financial immutable records despite future product modifications.</li>
        </ul>

        {/* Dynamic Image Carousel */}
        <h2 className="text-2xl font-bold mb-6 text-white border-b border-zinc-800 pb-2 mt-12">Application Interface</h2>
        <ImageCarousel />
      </>
    )
  }
};

const ProjectDetail = () => {
  const { id } = useParams();
  const project = projectsData[id];

  if (!project) {
    return <Navigate to="/" replace />;
  }

  return (
    <div className="min-h-screen bg-[#09090b] text-white pt-20 pb-24">
      <div className="container mx-auto px-6 max-w-5xl">
        {/* Back Button */}
        <Link 
          to="/" 
          className="inline-flex items-center gap-2 text-cyan-500 hover:text-cyan-400 font-medium mb-10 transition-colors duration-300"
        >
          <ArrowLeft size={20} />
          ← Back to Portfolio
        </Link>
        
        {project.headerMedia}

        {/* Content Container */}
        <div className="max-w-3xl mx-auto px-4 md:px-0 prose prose-invert prose-cyan max-w-none">
          <h1 className="text-4xl md:text-5xl font-bold mb-6 text-white text-center md:text-left">{project.title}</h1>
          
          <h3 className="text-xl font-semibold mb-3 text-white">Tech Stack</h3>
          <div className="flex flex-wrap gap-2 mb-10">
            {project.techStack.map(tech => (
              <span key={tech} className="inline-flex items-center gap-1.5 px-3 py-1 bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 rounded-full text-sm font-medium">
                {tech === 'MongoDB' || tech === 'FastAPI' || tech === 'Pinecone' ? <Database size={14} /> : null}
                {tech === 'React' ? <Component size={14} /> : null}
                {tech === 'Node.js' || tech === 'Python' ? <Server size={14} /> : null}
                {tech}
              </span>
            ))}
          </div>

          {project.content}

          {/* Footer CTA */}
          <div className="mt-16 text-center md:text-left">
            <a 
              href={project.github} 
              target="_blank" 
              rel="noopener noreferrer"
              className="inline-flex items-center justify-center gap-2 bg-zinc-100 hover:bg-white text-zinc-900 py-3 px-6 rounded-lg font-semibold transition-colors duration-300"
            >
              <GitBranch size={20} />
              View Source Code on GitHub
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProjectDetail;
